### ISSUE TITLE
Module dependency graph

### ISSUE THREAD

**Issue by dergraaf** [dergraaf/library-builder#10]
Add e.g. a [Graphviz](http://www.graphviz.org/) output to show the dependency of the modules within a project.

**Comment by salkinium** [comment]
Be careful what you wish for. Example from yotta:
<img width="734" src="https://cloud.githubusercontent.com/assets/163066/19349615/da2771f4-914b-11e6-82ea-caf38f05e7e9.png">

**Comment by dergraaf** [comment]
I only what to know what mess other people have produced :smile:

**Comment by salkinium** [comment]
Does this include module dependencies on options as well? Cos that could become quite messy and potentially recursive.

**Comment by dergraaf** [comment]
> Does this include module dependencies on options as well?

No. Only the dependencies of modules for a given set of repository options.
