### ISSUE TITLE
Share module environment with sub modules

### ISSUE THREAD

**Issue by salkinium** [dergraaf/library-builder#11]
I want to share the `env.substitution` and `env.outbasepath` with the submodules.
This would eliminate copy paste code, or overly generalized "env" builder methods.

Example: Each ADC instance consumes the `max_frequency` substitution, which is however, not dependant on the instance, only on family. It could therefore be computed in the module and shared with its submodules.

``` py
properties["max_frequency"] = 36000000 if target.family in ["f4", "f7"] else 14000000
```

cc @dergraaf

**Comment by salkinium** [comment]
And yes, that data should perhaps be placed in the device files, but that's another issue.

**Comment by dergraaf** [comment]
For submodules declared in the same file as the module (e.g. the UART modules) that can be done easily by forwarding the information to the submodule constructor. For submodules declared in a separate file, there is currently no good way of doing that.
