### ISSUE TITLE
Support relative paths above module

### ISSUE THREAD

**Issue by salkinium** [dergraaf/library-builder#17]
```
env.template("../board.cpp.in", "board.cpp")
```
fails because of 
```
environment = RelEnvironment(loader=jinja2.FileSystemLoader(self.__modulepath),
```
is loaded with the module path and can't resolve files above it.
`env.copy` works fine, because it uses a different mechanism.
```
env.copy("../nucleo32_arduino.hpp", "nucleo32_arduino.hpp")
```

Is this something we want to support?

**Comment by salkinium** [comment]
I think I'll implement this feature by making the `RelEnvironment` allow loading any file inside the repository.

**Comment by dergraaf** [comment]
> Is this something we want to support?

Yes, there is no reason to not support it.
