### ISSUE TITLE
Do not copy hidden files

### ISSUE THREAD

**Issue by salkinium** [dergraaf/library-builder#20]
`env.copy('.')` also copies hidden files and folders, like `.git` in git submodules, which messes with the git repository you want to commit the copied files in.

**Comment by salkinium** [comment]
Also copies `__pycache__` for example.

**Comment by dergraaf** [comment]
Yeah, I've noticed that too. I'm thinking about adding a default list of things to ignore. Although I'm not sure yet on how to fill that list.

Is it useful to inherit such a list from the repo to the modules and then submodules and allow each to append entries?

**Comment by salkinium** [comment]
> Is it useful to inherit such a list from the repo to the modules and then submodules and allow each to append entries?

Yes. We already share a lot of state with submodules, I think this won't be too surprising.

**Comment by salkinium** [comment]
I mean at the very least the `.lb` file that is currently executed should be in that ignore list by default.

**Comment by dergraaf** [comment]
I'm already working on it.

**Comment by salkinium** [comment]
Updates? \*poke\*
