### ISSUE TITLE
Colorize options output

### ISSUE THREAD

**Issue by salkinium** [dergraaf/library-builder#23]
They are hard to read in monocolor.
Some different colors for name, default, type and user choice would be helpful.

**Comment by dergraaf** [comment]
Do you have a suggestion for a color scheme? The default problem with colors is that there are users with light background on their terminal vs users with dark background. And also terminals which don't support colors.

**Comment by salkinium** [comment]
I think we should rather have a machine readable output, that then can be transformed into HTML etc. by a separate program. Cos it's not really lbuilds purpose to format this nicely.
