### ISSUE TITLE
Shared build tools from repository

### ISSUE THREAD

**Issue by ekiwi** [dergraaf/library-builder#6]
It will probably be necessary for repositories to provide some custom python build tools in order to extend the functionality offered by the `library-builder`.
Are there plan on how repositories can offer these tools in a way that modules from other repositories can also use them?

One example might be a tool that makes it possible to parse hardware descriptions and that might be required by several modules that provide hardware abstractions.

**Comment by dergraaf** [comment]
See [modm-platform](https://github.com/modm-io/modm-platform/blob/a853fc96c36dee3c430d0828ac2c5cb53a3ceab7/source/repo.lb) for an example on how to use standard Python imports for this.
