### ISSUE TITLE
Unittests for library-builder modules

### ISSUE THREAD

**Issue by ekiwi** [dergraaf/library-builder#8]
One important feature of the current `xpcc` build system is it's unittest support, which I have even used in several projects that would not require `xpcc` otherwise.

Are there plans to add support for C++ (and maybe python) unittests for library-builder modules?
We should probably also test if all dependencies have been specified correctly by building modules separately with minimal dependencies: If the build fails, the author might have missed a dependency.

**Comment by salkinium** [comment]
I think this is off-topic and has already been solved in modm via the `modm:test` modules.
