### ISSUE TITLE
Support Enum parameters

### ISSUE THREAD

**Issue by ekiwi** [dergraaf/library-builder#9]
As library-builder is using Python3, we could make use of native python Enums for parameters.
For example for the [target architecture](https://github.com/dergraaf/library-builder/blob/f52f11c9bae0496747e603788b2f1db9610193ed/example/repo2/repo.lb#L7).
Using Enums makes it easier for users to discovery supported options and allows `lbuild` to quickly discover invalid arguments.

The `xpcc` device/driver files already support [enum arguments](https://github.com/roboterclubaachen/xpcc/blob/fc5458a471d761296f4f2778ceb81f52991fba0e/tools/device_files/driver.py#L355) (however, in a custom implementation, as we are using XML and Python2) for the same reasons as mentioned above.

**Comment by dergraaf** [comment]
With the commits before 32eb7d5e755f16fddf564b48db3353279ed5d48f enum options are now supported. Either with string lists or with Python enums directly.
